# Generated by Django 5.1.4 on 2025-01-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.paymentcategory'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.paymenttype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='related_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.bankaccount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='related_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.person'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payments.status'),
        ),
        migrations.AlterField(
            model_name='paymentfile',
            name='file',
            field=models.FileField(upload_to='files_record/payment_files/'),
        ),
        migrations.AlterField(
            model_name='paymentfile',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='payments.payment'),
        ),
    ]
