# Generated by Django 5.1.4 on 2025-01-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_olympiad_remove_course_description_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='related_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='payments.olympiad'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='payments.teacher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='payments.teacher'),
        ),
        migrations.AlterField(
            model_name='studentagreement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.course'),
        ),
        migrations.AlterField(
            model_name='studentagreement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.student'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.product'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.teacher'),
        ),
    ]
