# Generated by Django 5.1.4 on 2025-01-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_course_related_product_alter_course_olympiad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='payments.person'),
            preserve_default=False,
        ),
    ]
