# Generated by Django 5.1.4 on 2025-01-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_student_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='payments.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='payments.person'),
        ),
    ]
