# Generated by Django 5.1.4 on 2025-01-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_installmentstatus_paymentagreement_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
