# Generated by Django 5.1.4 on 2025-01-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_excelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='course',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='installment',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='installmentstatus',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='payment',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='paymentagreement',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='paymentfile',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='person',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='product',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='status',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='student',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='studentagreement',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
        migrations.AddField(
            model_name='teacheragreement',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.excelupload'),
        ),
    ]
